package afternow.cn.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import afternow.cn.entity.AdminAction;
import afternow.cn.entity.example.AdminActionExample;

public interface AdminActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_action
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int countByExample(AdminActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_action
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int deleteByExample(AdminActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_action
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int deleteByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_action
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int insert(AdminAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_action
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int insertSelective(AdminAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_action
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    List<AdminAction> selectByExample(AdminActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_action
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    AdminAction selectByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_action
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") AdminAction record, @Param("example") AdminActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_action
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByExample(@Param("record") AdminAction record, @Param("example") AdminActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_action
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByPrimaryKeySelective(AdminAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_action
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByPrimaryKey(AdminAction record);
}