package afternow.cn.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import afternow.cn.entity.GoodsCat;
import afternow.cn.entity.example.GoodsCatExample;

public interface GoodsCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cat
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int countByExample(GoodsCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cat
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int deleteByExample(GoodsCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cat
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cat
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int insert(GoodsCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cat
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int insertSelective(GoodsCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cat
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    List<GoodsCat> selectByExample(GoodsCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cat
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    GoodsCat selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cat
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") GoodsCat record, @Param("example") GoodsCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cat
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByExample(@Param("record") GoodsCat record, @Param("example") GoodsCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cat
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cat
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByPrimaryKey(GoodsCat record);
}