package afternow.cn.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import afternow.cn.entity.LinkGoods;
import afternow.cn.entity.example.LinkGoodsExample;

public interface LinkGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_goods
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int countByExample(LinkGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_goods
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int deleteByExample(LinkGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_goods
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int insert(LinkGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_goods
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int insertSelective(LinkGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_goods
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    List<LinkGoods> selectByExample(LinkGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_goods
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") LinkGoods record, @Param("example") LinkGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_goods
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByExample(@Param("record") LinkGoods record, @Param("example") LinkGoodsExample example);
}