package afternow.cn.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import afternow.cn.entity.OrderLog;
import afternow.cn.entity.example.OrderLogExample;

public interface OrderLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int countByExample(OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int deleteByExample(OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int deleteByPrimaryKey(Integer orderlogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int insert(OrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int insertSelective(OrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    List<OrderLog> selectByExample(OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    OrderLog selectByPrimaryKey(Integer orderlogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderLog record, @Param("example") OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByExample(@Param("record") OrderLog record, @Param("example") OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByPrimaryKeySelective(OrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByPrimaryKey(OrderLog record);
}