package afternow.cn.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import afternow.cn.entity.Searchengine;
import afternow.cn.entity.example.SearchengineExample;

public interface SearchengineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchengine
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int countByExample(SearchengineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchengine
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int deleteByExample(SearchengineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchengine
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int insert(Searchengine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchengine
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int insertSelective(Searchengine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchengine
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    List<Searchengine> selectByExample(SearchengineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchengine
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") Searchengine record, @Param("example") SearchengineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchengine
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByExample(@Param("record") Searchengine record, @Param("example") SearchengineExample example);
}