package afternow.cn.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import afternow.cn.entity.UserRank;
import afternow.cn.entity.example.UserRankExample;

public interface UserRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int countByExample(UserRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int deleteByExample(UserRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int deleteByPrimaryKey(Integer rankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int insert(UserRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int insertSelective(UserRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    List<UserRank> selectByExample(UserRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    UserRank selectByPrimaryKey(Integer rankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserRank record, @Param("example") UserRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByExample(@Param("record") UserRank record, @Param("example") UserRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByPrimaryKeySelective(UserRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbggenerated Wed May 09 19:30:24 CST 2018
     */
    int updateByPrimaryKey(UserRank record);
}