#118.25.71.46
server: 
  port: 10017
  servlet:
    context-path: /
spring: 
  application:
    name: fruit-uums
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:10010/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true 

