package afternow.cn.entity;

public class AdminAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_action.action_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer actionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_action.parent_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_action.action_code
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String actionCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_action.action_id
     *
     * @return the value of admin_action.action_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_action.action_id
     *
     * @param actionId the value for admin_action.action_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_action.parent_id
     *
     * @return the value of admin_action.parent_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_action.parent_id
     *
     * @param parentId the value for admin_action.parent_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_action.action_code
     *
     * @return the value of admin_action.action_code
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getActionCode() {
        return actionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_action.action_code
     *
     * @param actionCode the value for admin_action.action_code
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setActionCode(String actionCode) {
        this.actionCode = actionCode == null ? null : actionCode.trim();
    }
}