package afternow.cn.entity;

import java.io.Serializable;

public class Category implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cat_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.parent_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cat_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String catName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.keywords
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cat_desc
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String catDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.sort_order
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String sortOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cat_id
     *
     * @return the value of category.cat_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cat_id
     *
     * @param catId the value for category.cat_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setCatId(Integer catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.parent_id
     *
     * @return the value of category.parent_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.parent_id
     *
     * @param parentId the value for category.parent_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cat_name
     *
     * @return the value of category.cat_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getCatName() {
        return catName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cat_name
     *
     * @param catName the value for category.cat_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setCatName(String catName) {
        this.catName = catName == null ? null : catName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.keywords
     *
     * @return the value of category.keywords
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.keywords
     *
     * @param keywords the value for category.keywords
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cat_desc
     *
     * @return the value of category.cat_desc
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getCatDesc() {
        return catDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cat_desc
     *
     * @param catDesc the value for category.cat_desc
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setCatDesc(String catDesc) {
        this.catDesc = catDesc == null ? null : catDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.sort_order
     *
     * @return the value of category.sort_order
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.sort_order
     *
     * @param sortOrder the value for category.sort_order
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setSortOrder(String sortOrder) {
        this.sortOrder = sortOrder == null ? null : sortOrder.trim();
    }
}