package afternow.cn.entity;

import java.util.Date;

public class FavoutableActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favoutable_activity.act_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favoutable_activity.act_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String actName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favoutable_activity.start_time
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favoutable_activity.end_time
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favoutable_activity.user_rank
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String userRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favoutable_activity.act_range
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer actRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favoutable_activity.act_range_ext
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String actRangeExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favoutable_activity.min_amount
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Long minAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favoutable_activity.max_amount
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Long maxAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favoutable_activity.act_type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer actType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favoutable_activity.act_type_ext
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Date actTypeExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favoutable_activity.sort_order
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favoutable_activity.gift
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String gift;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favoutable_activity.act_id
     *
     * @return the value of favoutable_activity.act_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favoutable_activity.act_id
     *
     * @param actId the value for favoutable_activity.act_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setActId(Integer actId) {
        this.actId = actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favoutable_activity.act_name
     *
     * @return the value of favoutable_activity.act_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getActName() {
        return actName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favoutable_activity.act_name
     *
     * @param actName the value for favoutable_activity.act_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setActName(String actName) {
        this.actName = actName == null ? null : actName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favoutable_activity.start_time
     *
     * @return the value of favoutable_activity.start_time
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favoutable_activity.start_time
     *
     * @param startTime the value for favoutable_activity.start_time
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favoutable_activity.end_time
     *
     * @return the value of favoutable_activity.end_time
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favoutable_activity.end_time
     *
     * @param endTime the value for favoutable_activity.end_time
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favoutable_activity.user_rank
     *
     * @return the value of favoutable_activity.user_rank
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getUserRank() {
        return userRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favoutable_activity.user_rank
     *
     * @param userRank the value for favoutable_activity.user_rank
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setUserRank(String userRank) {
        this.userRank = userRank == null ? null : userRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favoutable_activity.act_range
     *
     * @return the value of favoutable_activity.act_range
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getActRange() {
        return actRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favoutable_activity.act_range
     *
     * @param actRange the value for favoutable_activity.act_range
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setActRange(Integer actRange) {
        this.actRange = actRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favoutable_activity.act_range_ext
     *
     * @return the value of favoutable_activity.act_range_ext
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getActRangeExt() {
        return actRangeExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favoutable_activity.act_range_ext
     *
     * @param actRangeExt the value for favoutable_activity.act_range_ext
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setActRangeExt(String actRangeExt) {
        this.actRangeExt = actRangeExt == null ? null : actRangeExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favoutable_activity.min_amount
     *
     * @return the value of favoutable_activity.min_amount
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Long getMinAmount() {
        return minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favoutable_activity.min_amount
     *
     * @param minAmount the value for favoutable_activity.min_amount
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setMinAmount(Long minAmount) {
        this.minAmount = minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favoutable_activity.max_amount
     *
     * @return the value of favoutable_activity.max_amount
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Long getMaxAmount() {
        return maxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favoutable_activity.max_amount
     *
     * @param maxAmount the value for favoutable_activity.max_amount
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setMaxAmount(Long maxAmount) {
        this.maxAmount = maxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favoutable_activity.act_type
     *
     * @return the value of favoutable_activity.act_type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getActType() {
        return actType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favoutable_activity.act_type
     *
     * @param actType the value for favoutable_activity.act_type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setActType(Integer actType) {
        this.actType = actType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favoutable_activity.act_type_ext
     *
     * @return the value of favoutable_activity.act_type_ext
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Date getActTypeExt() {
        return actTypeExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favoutable_activity.act_type_ext
     *
     * @param actTypeExt the value for favoutable_activity.act_type_ext
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setActTypeExt(Date actTypeExt) {
        this.actTypeExt = actTypeExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favoutable_activity.sort_order
     *
     * @return the value of favoutable_activity.sort_order
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favoutable_activity.sort_order
     *
     * @param sortOrder the value for favoutable_activity.sort_order
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favoutable_activity.gift
     *
     * @return the value of favoutable_activity.gift
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getGift() {
        return gift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favoutable_activity.gift
     *
     * @param gift the value for favoutable_activity.gift
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setGift(String gift) {
        this.gift = gift == null ? null : gift.trim();
    }
}