package afternow.cn.entity;

public class GoodsAttribute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attribute.attr_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer attrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attribute.cat_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attribute.attr_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String attrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attribute.attr_input_type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String attrInputType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attribute.attr_type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer attrType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attribute.attr_values
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String attrValues;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attribute.attr_index
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer attrIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attribute.sort_order
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attribute.is_linked
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer isLinked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attribute.attr_group
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer attrGroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attribute.attr_id
     *
     * @return the value of goods_attribute.attr_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attribute.attr_id
     *
     * @param attrId the value for goods_attribute.attr_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attribute.cat_id
     *
     * @return the value of goods_attribute.cat_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attribute.cat_id
     *
     * @param catId the value for goods_attribute.cat_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setCatId(Integer catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attribute.attr_name
     *
     * @return the value of goods_attribute.attr_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attribute.attr_name
     *
     * @param attrName the value for goods_attribute.attr_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName == null ? null : attrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attribute.attr_input_type
     *
     * @return the value of goods_attribute.attr_input_type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getAttrInputType() {
        return attrInputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attribute.attr_input_type
     *
     * @param attrInputType the value for goods_attribute.attr_input_type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setAttrInputType(String attrInputType) {
        this.attrInputType = attrInputType == null ? null : attrInputType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attribute.attr_type
     *
     * @return the value of goods_attribute.attr_type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getAttrType() {
        return attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attribute.attr_type
     *
     * @param attrType the value for goods_attribute.attr_type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setAttrType(Integer attrType) {
        this.attrType = attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attribute.attr_values
     *
     * @return the value of goods_attribute.attr_values
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getAttrValues() {
        return attrValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attribute.attr_values
     *
     * @param attrValues the value for goods_attribute.attr_values
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setAttrValues(String attrValues) {
        this.attrValues = attrValues == null ? null : attrValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attribute.attr_index
     *
     * @return the value of goods_attribute.attr_index
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getAttrIndex() {
        return attrIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attribute.attr_index
     *
     * @param attrIndex the value for goods_attribute.attr_index
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setAttrIndex(Integer attrIndex) {
        this.attrIndex = attrIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attribute.sort_order
     *
     * @return the value of goods_attribute.sort_order
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attribute.sort_order
     *
     * @param sortOrder the value for goods_attribute.sort_order
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attribute.is_linked
     *
     * @return the value of goods_attribute.is_linked
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getIsLinked() {
        return isLinked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attribute.is_linked
     *
     * @param isLinked the value for goods_attribute.is_linked
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setIsLinked(Integer isLinked) {
        this.isLinked = isLinked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attribute.attr_group
     *
     * @return the value of goods_attribute.attr_group
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getAttrGroup() {
        return attrGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attribute.attr_group
     *
     * @param attrGroup the value for goods_attribute.attr_group
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setAttrGroup(Integer attrGroup) {
        this.attrGroup = attrGroup;
    }
}