package afternow.cn.entity;

import java.math.BigDecimal;

public class GroupGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_goods.goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_goods.parent_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_goods.goods_price
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private BigDecimal goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_goods.admin_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer adminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_goods.goods_id
     *
     * @return the value of group_goods.goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_goods.goods_id
     *
     * @param goodsId the value for group_goods.goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_goods.parent_id
     *
     * @return the value of group_goods.parent_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_goods.parent_id
     *
     * @param parentId the value for group_goods.parent_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_goods.goods_price
     *
     * @return the value of group_goods.goods_price
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_goods.goods_price
     *
     * @param goodsPrice the value for group_goods.goods_price
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_goods.admin_id
     *
     * @return the value of group_goods.admin_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_goods.admin_id
     *
     * @param adminId the value for group_goods.admin_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
}