package afternow.cn.entity;

public class LinkGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_goods.goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_goods.link_goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer linkGoodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_goods.is_double
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer isDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_goods.admin_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer adminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_goods.goods_id
     *
     * @return the value of link_goods.goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_goods.goods_id
     *
     * @param goodsId the value for link_goods.goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_goods.link_goods_id
     *
     * @return the value of link_goods.link_goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getLinkGoodsId() {
        return linkGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_goods.link_goods_id
     *
     * @param linkGoodsId the value for link_goods.link_goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setLinkGoodsId(Integer linkGoodsId) {
        this.linkGoodsId = linkGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_goods.is_double
     *
     * @return the value of link_goods.is_double
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getIsDouble() {
        return isDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_goods.is_double
     *
     * @param isDouble the value for link_goods.is_double
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setIsDouble(Integer isDouble) {
        this.isDouble = isDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_goods.admin_id
     *
     * @return the value of link_goods.admin_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_goods.admin_id
     *
     * @param adminId the value for link_goods.admin_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
}