package afternow.cn.entity;

public class Pack {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack.pack_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer packId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack.pack_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String packName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack.pack_img
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String packImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack.pack_fee
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Long packFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack.free_money
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Long freeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack.pack_desc
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String packDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack.pack_id
     *
     * @return the value of pack.pack_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getPackId() {
        return packId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack.pack_id
     *
     * @param packId the value for pack.pack_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setPackId(Integer packId) {
        this.packId = packId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack.pack_name
     *
     * @return the value of pack.pack_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getPackName() {
        return packName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack.pack_name
     *
     * @param packName the value for pack.pack_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setPackName(String packName) {
        this.packName = packName == null ? null : packName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack.pack_img
     *
     * @return the value of pack.pack_img
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getPackImg() {
        return packImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack.pack_img
     *
     * @param packImg the value for pack.pack_img
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setPackImg(String packImg) {
        this.packImg = packImg == null ? null : packImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack.pack_fee
     *
     * @return the value of pack.pack_fee
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Long getPackFee() {
        return packFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack.pack_fee
     *
     * @param packFee the value for pack.pack_fee
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setPackFee(Long packFee) {
        this.packFee = packFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack.free_money
     *
     * @return the value of pack.free_money
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Long getFreeMoney() {
        return freeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack.free_money
     *
     * @param freeMoney the value for pack.free_money
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setFreeMoney(Long freeMoney) {
        this.freeMoney = freeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack.pack_desc
     *
     * @return the value of pack.pack_desc
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getPackDesc() {
        return packDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack.pack_desc
     *
     * @param packDesc the value for pack.pack_desc
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setPackDesc(String packDesc) {
        this.packDesc = packDesc == null ? null : packDesc.trim();
    }
}