package afternow.cn.entity;

public class Products {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.product_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.goods_attr
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String goodsAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.product_sn
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String productSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.product_number
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer productNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.product_id
     *
     * @return the value of products.product_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.product_id
     *
     * @param productId the value for products.product_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.goods_id
     *
     * @return the value of products.goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.goods_id
     *
     * @param goodsId the value for products.goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.goods_attr
     *
     * @return the value of products.goods_attr
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getGoodsAttr() {
        return goodsAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.goods_attr
     *
     * @param goodsAttr the value for products.goods_attr
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setGoodsAttr(String goodsAttr) {
        this.goodsAttr = goodsAttr == null ? null : goodsAttr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.product_sn
     *
     * @return the value of products.product_sn
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getProductSn() {
        return productSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.product_sn
     *
     * @param productSn the value for products.product_sn
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setProductSn(String productSn) {
        this.productSn = productSn == null ? null : productSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.product_number
     *
     * @return the value of products.product_number
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.product_number
     *
     * @param productNumber the value for products.product_number
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setProductNumber(Integer productNumber) {
        this.productNumber = productNumber;
    }
}