package afternow.cn.entity;

public class Searchengine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column searchengine.date
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column searchengine.searchengine
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String searchengine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column searchengine.count
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column searchengine.date
     *
     * @return the value of searchengine.date
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column searchengine.date
     *
     * @param date the value for searchengine.date
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column searchengine.searchengine
     *
     * @return the value of searchengine.searchengine
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getSearchengine() {
        return searchengine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column searchengine.searchengine
     *
     * @param searchengine the value for searchengine.searchengine
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setSearchengine(String searchengine) {
        this.searchengine = searchengine == null ? null : searchengine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column searchengine.count
     *
     * @return the value of searchengine.count
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column searchengine.count
     *
     * @param count the value for searchengine.count
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}