package afternow.cn.entity;

public class Template {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.filename
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.region
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.library
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String library;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.sort_order
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.number
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.theme
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.remarks
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.filename
     *
     * @return the value of template.filename
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.filename
     *
     * @param filename the value for template.filename
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.region
     *
     * @return the value of template.region
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.region
     *
     * @param region the value for template.region
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.library
     *
     * @return the value of template.library
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getLibrary() {
        return library;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.library
     *
     * @param library the value for template.library
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setLibrary(String library) {
        this.library = library == null ? null : library.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.sort_order
     *
     * @return the value of template.sort_order
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.sort_order
     *
     * @param sortOrder the value for template.sort_order
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setSortOrder(String sortOrder) {
        this.sortOrder = sortOrder == null ? null : sortOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.number
     *
     * @return the value of template.number
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.number
     *
     * @param number the value for template.number
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.type
     *
     * @return the value of template.type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.type
     *
     * @param type the value for template.type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.theme
     *
     * @return the value of template.theme
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.theme
     *
     * @param theme the value for template.theme
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.remarks
     *
     * @return the value of template.remarks
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.remarks
     *
     * @param remarks the value for template.remarks
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}