package afternow.cn.entity;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

@SuppressWarnings("serial")
public class Users implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    @NotEmpty(message="密码不能为空")
    @Size(min=6,max=10,message = "密码长度必须6到10位")
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    @Email
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.question
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.answer
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.sex
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.birthday
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_money
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private BigDecimal userMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.frozen_money
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private BigDecimal frozenMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.pay_points
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer payPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.rank_points
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer rankPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.address_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.reg_time
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.last_login
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.last_time
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.last_ip
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String lastIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.visit_count
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer visitCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_rank
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer userRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.is_special
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer isSpecial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.parent_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.alias
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.qq
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.office_phone
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String officePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.home_phone
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String homePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.mobile_phone
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.is_validated
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer isValidated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.credit_line
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Long creditLine;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_name
     *
     * @return the value of users.user_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_name
     *
     * @param userName the value for users.user_name
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.question
     *
     * @return the value of users.question
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.question
     *
     * @param question the value for users.question
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.answer
     *
     * @return the value of users.answer
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.answer
     *
     * @param answer the value for users.answer
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.sex
     *
     * @return the value of users.sex
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.sex
     *
     * @param sex the value for users.sex
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.birthday
     *
     * @return the value of users.birthday
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.birthday
     *
     * @param birthday the value for users.birthday
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_money
     *
     * @return the value of users.user_money
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public BigDecimal getUserMoney() {
        return userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_money
     *
     * @param userMoney the value for users.user_money
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setUserMoney(BigDecimal userMoney) {
        this.userMoney = userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.frozen_money
     *
     * @return the value of users.frozen_money
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public BigDecimal getFrozenMoney() {
        return frozenMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.frozen_money
     *
     * @param frozenMoney the value for users.frozen_money
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setFrozenMoney(BigDecimal frozenMoney) {
        this.frozenMoney = frozenMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.pay_points
     *
     * @return the value of users.pay_points
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getPayPoints() {
        return payPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.pay_points
     *
     * @param payPoints the value for users.pay_points
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setPayPoints(Integer payPoints) {
        this.payPoints = payPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.rank_points
     *
     * @return the value of users.rank_points
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getRankPoints() {
        return rankPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.rank_points
     *
     * @param rankPoints the value for users.rank_points
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setRankPoints(Integer rankPoints) {
        this.rankPoints = rankPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.address_id
     *
     * @return the value of users.address_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.address_id
     *
     * @param addressId the value for users.address_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.reg_time
     *
     * @return the value of users.reg_time
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.reg_time
     *
     * @param regTime the value for users.reg_time
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setRegTime(String regTime) {
        this.regTime = regTime == null ? null : regTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.last_login
     *
     * @return the value of users.last_login
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.last_login
     *
     * @param lastLogin the value for users.last_login
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setLastLogin(String lastLogin) {
        this.lastLogin = lastLogin == null ? null : lastLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.last_time
     *
     * @return the value of users.last_time
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.last_time
     *
     * @param lastTime the value for users.last_time
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setLastTime(String lastTime) {
        this.lastTime = lastTime == null ? null : lastTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.last_ip
     *
     * @return the value of users.last_ip
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.last_ip
     *
     * @param lastIp the value for users.last_ip
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.visit_count
     *
     * @return the value of users.visit_count
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getVisitCount() {
        return visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.visit_count
     *
     * @param visitCount the value for users.visit_count
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setVisitCount(Integer visitCount) {
        this.visitCount = visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_rank
     *
     * @return the value of users.user_rank
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getUserRank() {
        return userRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_rank
     *
     * @param userRank the value for users.user_rank
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setUserRank(Integer userRank) {
        this.userRank = userRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.is_special
     *
     * @return the value of users.is_special
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getIsSpecial() {
        return isSpecial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.is_special
     *
     * @param isSpecial the value for users.is_special
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setIsSpecial(Integer isSpecial) {
        this.isSpecial = isSpecial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.parent_id
     *
     * @return the value of users.parent_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.parent_id
     *
     * @param parentId the value for users.parent_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.alias
     *
     * @return the value of users.alias
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.alias
     *
     * @param alias the value for users.alias
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.qq
     *
     * @return the value of users.qq
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.qq
     *
     * @param qq the value for users.qq
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.office_phone
     *
     * @return the value of users.office_phone
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getOfficePhone() {
        return officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.office_phone
     *
     * @param officePhone the value for users.office_phone
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone == null ? null : officePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.home_phone
     *
     * @return the value of users.home_phone
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getHomePhone() {
        return homePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.home_phone
     *
     * @param homePhone the value for users.home_phone
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone == null ? null : homePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.mobile_phone
     *
     * @return the value of users.mobile_phone
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.mobile_phone
     *
     * @param mobilePhone the value for users.mobile_phone
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.is_validated
     *
     * @return the value of users.is_validated
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getIsValidated() {
        return isValidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.is_validated
     *
     * @param isValidated the value for users.is_validated
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setIsValidated(Integer isValidated) {
        this.isValidated = isValidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.credit_line
     *
     * @return the value of users.credit_line
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Long getCreditLine() {
        return creditLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.credit_line
     *
     * @param creditLine the value for users.credit_line
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setCreditLine(Long creditLine) {
        this.creditLine = creditLine;
    }
}