package afternow.cn.entity;

public class UserFeed {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feed.feed_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer feedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feed.user_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feed.value_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer valueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feed.goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feed.feed_type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer feedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feed.Is_feed
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    private Integer isFeed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feed.feed_id
     *
     * @return the value of user_feed.feed_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getFeedId() {
        return feedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feed.feed_id
     *
     * @param feedId the value for user_feed.feed_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setFeedId(Integer feedId) {
        this.feedId = feedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feed.user_id
     *
     * @return the value of user_feed.user_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feed.user_id
     *
     * @param userId the value for user_feed.user_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feed.value_id
     *
     * @return the value of user_feed.value_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getValueId() {
        return valueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feed.value_id
     *
     * @param valueId the value for user_feed.value_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setValueId(Integer valueId) {
        this.valueId = valueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feed.goods_id
     *
     * @return the value of user_feed.goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feed.goods_id
     *
     * @param goodsId the value for user_feed.goods_id
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feed.feed_type
     *
     * @return the value of user_feed.feed_type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getFeedType() {
        return feedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feed.feed_type
     *
     * @param feedType the value for user_feed.feed_type
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setFeedType(Integer feedType) {
        this.feedType = feedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feed.Is_feed
     *
     * @return the value of user_feed.Is_feed
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public Integer getIsFeed() {
        return isFeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feed.Is_feed
     *
     * @param isFeed the value for user_feed.Is_feed
     *
     * @mbggenerated Wed May 09 17:09:45 CST 2018
     */
    public void setIsFeed(Integer isFeed) {
        this.isFeed = isFeed;
    }
}