server: 
  port: 10019
  servlet:
    context-path: /
spring:
  application:
    # 聚合服务监控
    name: fruit-turbine
  cloud:
    config:
      uri: http://localhost:10014
  rabbitmq:
    addresses: amqp://localhost:5672
    username: lb
    password: lb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/,http://localhost:10011/eureka/,http://localhost:10012/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

turbine:
  app-config: 
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
