server:
  port: 10016
  servlet:
    context-path: /
spring:
  application:
    name: fruit-order
  datasource:
    url: jdbc:mysql://localhost:3306/afternow?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: lyy@1551881752
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    addresses: amqp://localhost:5672
    host: localhost
    port: 5672
    username: lb
    password: lb
    connection-timeout: 5000
    publisher-confirms: true
    publisher-returns: true
    virtual-host: /
#  cloud:
#    stream:
#      bindings:
#        output:
#          destination: OrderInfoMessages
#          content-type: application/json
logging: 
  level: 
    afternow.cn.mapper: debug
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: afternow.cn.entity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true