server:
  port: 10020﻿
  servlet:
    context-path: /
spring:
  application:
    name: fruit-zipkin
  zipkin:
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:mysql://localhost:3306/afternow?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: lyy@1551881752
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 配置监控统计拦截的filters 去掉后监控页面sql 将无法统计 wall 用于防火墙
    druid:
      filters: stat,wall,log4j
      # 通过 connection-properties 属性来打开mergeSql 功能 慢sql 记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  cloud:
    config:
      uri: http://localhost:10014
  rabbitmq:
    addresses: amqp://localhost:5672
    username: 
    password: 
    connection-timeout: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/,http://localhost:10011/eureka/,http://localhost:10012/eureka/
