server:
  port: 10013
  servlet:
    context-path: /
spring:
  application:
    name: fruit-beans
  datasource:
    username: root
    password: lyy@1551881752
    url: jdbc:mysql://localhost:3306/senseguard?characterEncoding=utf-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/ 
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    appname: fruit-beans
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: afternow.cn.entity
logging:
  level:
    afternow.cn.mapper: debug
