server: 
  port: 10015
  servlet:
    context-path: /
spring: 
  application:
    name: fruit-goods
  zipkin:
    base-url: http://localhost:10020
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/afternow?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: lyy@1551881752
        # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 广播型消息订阅队列配置
  rabbitmq:
    addresses: amqp://localhost:5672
    username: lb
    password: lb
    connection-timeout: 5000
logging: 
  level: 
    afternow.cn.mapper: debug
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: afternow.cn.entity
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:10010/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    # 使用客户端IP注册
    prefer-ip-address: true 
    # 宿主host 
#    hostname: 
#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

access-file-path=classpath: access.json