server:
  port: 10016
  servlet:
    context-path: /
spring:
  application:
    name: fruit-order
  datasource:
    url: jdbc:mysql://localhost:3306/afternow?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: lyy@1551881752
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    addresses: amqp://localhost:5672
    username: lb
    password: lb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true